name: ✨ Update DEV.to Blog Posts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update DEV.to blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/yesiamrocks"
          max_post_count: 5
          comment_tag_name: "DEV-TO"
